// Code generated by protoc-gen-go. DO NOT EDIT.
// This is a simplified version for the demo

package pricingpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// PriceRequest - ข้อมูลสำหรับคำนวณราคา
type PriceRequest struct {
	PickupLat  float64 `protobuf:"fixed64,1,opt,name=pickup_lat,json=pickupLat,proto3" json:"pickup_lat,omitempty"`
	PickupLng  float64 `protobuf:"fixed64,2,opt,name=pickup_lng,json=pickupLng,proto3" json:"pickup_lng,omitempty"`
	DropoffLat float64 `protobuf:"fixed64,3,opt,name=dropoff_lat,json=dropoffLat,proto3" json:"dropoff_lat,omitempty"`
	DropoffLng float64 `protobuf:"fixed64,4,opt,name=dropoff_lng,json=dropoffLng,proto3" json:"dropoff_lng,omitempty"`
}

func (x *PriceRequest) GetPickupLat() float64 {
	if x != nil {
		return x.PickupLat
	}
	return 0
}

func (x *PriceRequest) GetPickupLng() float64 {
	if x != nil {
		return x.PickupLng
	}
	return 0
}

func (x *PriceRequest) GetDropoffLat() float64 {
	if x != nil {
		return x.DropoffLat
	}
	return 0
}

func (x *PriceRequest) GetDropoffLng() float64 {
	if x != nil {
		return x.DropoffLng
	}
	return 0
}

// PriceResponse - ผลการคำนวณราคา
type PriceResponse struct {
	Total       float64 `protobuf:"fixed64,1,opt,name=total,proto3" json:"total,omitempty"`
	BaseFare    float64 `protobuf:"fixed64,2,opt,name=base_fare,json=baseFare,proto3" json:"base_fare,omitempty"`
	DistanceFee float64 `protobuf:"fixed64,3,opt,name=distance_fee,json=distanceFee,proto3" json:"distance_fee,omitempty"`
	DistanceKm  float64 `protobuf:"fixed64,4,opt,name=distance_km,json=distanceKm,proto3" json:"distance_km,omitempty"`
	Currency    string  `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
}

func (x *PriceResponse) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *PriceResponse) GetBaseFare() float64 {
	if x != nil {
		return x.BaseFare
	}
	return 0
}

func (x *PriceResponse) GetDistanceFee() float64 {
	if x != nil {
		return x.DistanceFee
	}
	return 0
}

func (x *PriceResponse) GetDistanceKm() float64 {
	if x != nil {
		return x.DistanceKm
	}
	return 0
}

func (x *PriceResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

// PricingServiceClient is the client API for PricingService service
type PricingServiceClient interface {
	CalculatePrice(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (*PriceResponse, error)
}

type pricingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPricingServiceClient(cc grpc.ClientConnInterface) PricingServiceClient {
	return &pricingServiceClient{cc}
}

func (c *pricingServiceClient) CalculatePrice(ctx context.Context, in *PriceRequest, opts ...grpc.CallOption) (*PriceResponse, error) {
	out := new(PriceResponse)
	err := c.cc.Invoke(ctx, "/pricing.PricingService/CalculatePrice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PricingServiceServer is the server API for PricingService service
type PricingServiceServer interface {
	CalculatePrice(context.Context, *PriceRequest) (*PriceResponse, error)
	mustEmbedUnimplementedPricingServiceServer()
}

// UnimplementedPricingServiceServer must be embedded
type UnimplementedPricingServiceServer struct{}

func (UnimplementedPricingServiceServer) CalculatePrice(context.Context, *PriceRequest) (*PriceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculatePrice not implemented")
}
func (UnimplementedPricingServiceServer) mustEmbedUnimplementedPricingServiceServer() {}

// UnsafePricingServiceServer for forward compatibility
type UnsafePricingServiceServer interface {
	mustEmbedUnimplementedPricingServiceServer()
}

func RegisterPricingServiceServer(s grpc.ServiceRegistrar, srv PricingServiceServer) {
	s.RegisterService(&PricingService_ServiceDesc, srv)
}

func _PricingService_CalculatePrice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PriceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PricingServiceServer).CalculatePrice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pricing.PricingService/CalculatePrice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PricingServiceServer).CalculatePrice(ctx, req.(*PriceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PricingService_ServiceDesc is the service descriptor
var PricingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pricing.PricingService",
	HandlerType: (*PricingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CalculatePrice",
			Handler:    _PricingService_CalculatePrice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pricing.proto",
}
